version: "3.8"

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
      # - ./src:/myfolder/src => 모든 파일을 src폴더에 몰아넣고 공유하는 방법
    ports:
      - 3000:3000
  # 컴퓨터이름
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
