version: "3.7"

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5500:3000
    volumes:
      - ./index.js:/myfolder/index.js/
      - ./controllers/services/user.service.js:/myfolder/controllers/services/user.service.js
      - ./controllers/services/phone.service.js:/myfolder/controllers/services/phone.service.js
      - ./controllers/user.controller.js:/myfolder/controllers/user.controller.js
      - ./models/starbucksSchema.js:/myfolder/models/starbucksSchema.js
      - ./models/userSchema.js:/myfolder/models/userSchema.js
      - ./models/tokenSchema.js:/myfolder/models/tokenSchema.js

  # 컴퓨터이름
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
